In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\pondharshini\appdata\local\programs\python\python312\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pondharshini\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pondharshini\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pondharshini\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pondharshini\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
#From dictionary

In [4]:
data={'Name':['Alice','Bob'],'Age':[25,30]}

In [5]:
df=pd.DataFrame(data)

In [6]:
#From list of lists

In [7]:
lst=[['Alice',25],['Bob',30]]

In [8]:
df=pd.DataFrame(lst,columns=['Name','Age'])

In [9]:
df.head()  #First 5 rows

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
df.tail()  #last 5 rows

    Name  Age
0  Alice   25
1    Bob   30

In [11]:
df.info()  #Info about DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [12]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [13]:
#column selection

In [14]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [15]:
#Row selection by label and position

In [16]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [17]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [18]:
df[df['Age']>25] #Rows where Age>25

  Name  Age
1  Bob   30

In [19]:
df['gender']=['F','M',] #Add column

In [20]:
df.drop('Age',axis=1,inplace=True)  #remove column

In [21]:
df.isnull()

    Name  gender
0  False   False
1  False   False

In [22]:
df.dropna()

    Name gender
0  Alice      F
1    Bob      M

In [23]:
df.fillna(0)

    Name gender
0  Alice      F
1    Bob      M

In [24]:
df1=pd.DataFrame({'Key':['A','B','C'],'V1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'],'V2':[4,5,6]})

In [25]:
df1

  Key  V1
0   A   1
1   B   2
2   C   3

In [26]:
df2

  Key  V2
0   A   4
1   B   5
2   D   6

In [27]:
pd.merge(df1,df2,on='Key')

  Key  V1  V2
0   A   1   4
1   B   2   5

In [28]:
df1.join(df2,lsuffix='_left',rsuffix='_right')

  Key_left  V1 Key_right  V2
0        A   1         A   4
1        B   2         B   5
2        C   3         D   6

In [31]:
import os

In [32]:
os.getcwd()

'C:\\Users\\pondharshini\\OneDrive\\Desktop\\AIML'

In [34]:
df=pd.read_csv('data.csv')

In [35]:
df.to_csv('output.csv',index=False)

In [36]:
df.sort_values('age')

    name  age
0  alice   25
1    bob   30

In [37]:
df['age'].apply(lambda x:x+1)

0    26
1    31
Name: age, dtype: int64

In [38]:
df['name'].unique()

<StringArray>
['alice', 'bob']
Length: 2, dtype: str

In [40]:
df['age'].value_counts()

age
25    1
30    1
Name: count, dtype: int64